repos:
  - repo: local
    hooks:
      - id: docs-format-check
        name: Docs format check
        entry: python scripts/format_docs.py --check --width 120
        language: system
        pass_filenames: false
        files: "\\.(md|mdx|markdown)$"

